name: deploy

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - website/**

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Node.js dependencies
        run: |
          cd website
          yarn --frozen-lockfile

      - name: Put .env file
        run: echo "${{ secrets.ENV_FILE }}" > website/.env

      - name: Build
        run: |
          cd website
          yarn run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
